---

- name: create deploy group
  group: name={{deploy_group}}
  become: yes

- name: create deploy user
  user:
    name: "{{deploy_user}}"
    group: "{{deploy_group}}"
    append: yes
    createhome: no
  become: yes

- name: create me, add me to deploy group
  user:
    name: asymmetric
    groups: "{{deploy_group}}"
    append: yes
  become: yes

- name: create deploy directory
  file:
    path: /meltwater/kermit
    state: directory
    owner: "{{deploy_user}}"
    group: "{{deploy_group}}"
    mode: 0774
  become: yes

- name: install packages
  apt: name={{item}}
  with_items:
    - vim
    - sqlite3
  become: yes

- name: add sudoers rules
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/kermit
    validate: "visudo -cf %s"
  become: yes
